%vig contains ciphertext in the form of alphanumeric numbers
vig=uint8('MWHPBYTSUWHLZHTZFLEOASRVZSBHURSEARSLIXHLFLESMHLPRXTSQHILDCOAQROYFLEEMFLPPSWYIMTSNMGMDSTSQVWLEARTFXEYMPLZHIRTFMNWQXTPDWAWYSSENMGPZSURTXOMQPERUFLPMGRZEWTSQVOZYMTHMWAYURCZZGETHEBWKWTFBMDETMNRFSHLHIDZZIBFFLECQELTLIDPHINTZLIDBENTOLESMHNZFAAYFIDEAWMFPKEETICCQEMJBEPPDFYDTYTEURGETIBZAOWSUPEETIIYWAADIITSQHRPIMNSUWBCQETSMRDZBINPPXHPPSOCURSEMRTWKEWLDQWLHIOQDILTQJFWAAEOFLRZGKHSUQANAPOFDPEDEGRFELEOXSOVURGHAQAYIMTSIMSAKLATDENOMPIYQHFLOIWLEWTLZHIYSSUEEMDPALCZYVAOQWHPNIGLZMNLPVELDCWSURIYSWOCFSFGAMCPUXHZGKHEULELDHYZGGOXQMNOACOFFLIYWCOFOSUWPGOXQECCAWSLZHHLHIAWASKLFSUCWMTNTINDURKTFWGZFFLZOOEOGTAYPMTHMWMCETACESNDFLEHUJEZRENPUKHMAYRZZXHPEEMPRPOZDQRDIESLISROESMPILAEPMSNAYNEQRAYOIDMKXHPBEREKCOFIIRPEYPAAWEOFSCLXPEGQVYZZICZYVAOQFUEIMTSESMPISMPZSNPGWEOUXIYEXIYOXIGQPYDTIWLEEWZYENZREBZGXTSUVTJNYTWASKTZKMFOLOWPIRZZIHLPXHPUQPCQWSTARTSMXTSQVEHMWDFEXIYFLENDIADQWOQTIRQMGEHURSEARFZXPOHQHHPDHOHZXHPBESDMKEETISPMQAEQYRCQTATDNOMEAECQENLXQODFHATXCICDMTLFMOYHMCEAVYXMRSTARSHQVEZXHFWMXSMGMLEUROCFLECQEBZGXSLZHWPDIFLXPIYSXOAUICPEXHPBPADFIRQXEKPPGOYEXAYFPYQDSMNQMLTZKSLZHWLXPS');
vig=vig-65;
vig=double(vig);

%key is a vector containing key MEAL as calculated by hand
key=[12 4 0 11];

%iterate over an i number of shifts for the length of the key, 4
for i=1:4
    
    %for every 4th letter in the ciphertext (vig), apply shift key(i)
    for j=0:floor((length(vig)/4))-1
        %decryptv contains the decrypted message
       decryptv(1,i+4*j)=mod(vig(i+4*j)-key(i),26);
    
    end
    

end
    %print the decrypted message
    char(decryptv+65)
    
    
    %asheputhishandtothedoorknobwinstonsawthathehadleftthediaryopenonthetabledownwithbigbrotherwas
n1=sum([49 15 30 37 87 44 24 50 54  4 16 55 56 27 45 59 41 41 62 52 27 12 43 34 38 45 ]);
n_i1=[49270];
dude1=n_i1/(n1*(n1-1))
m=(0.0667-1/26)/(dude1-1/26)
%4.3262
